repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: flake8
        files: datatableview
        exclude: tests/*
        args: ['--config=tox.ini']
      - id: fix-encoding-pragma
      - id: end-of-file-fixer
        exclude: .idea/*
      - id: trailing-whitespace
        exclude: .idea/*
      - id: mixed-line-ending
        exclude: .idea/*
      - id: double-quote-string-fixer
        exclude: .idea/*
      - id: check-json
        files: .gitignore
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.16  # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
        files: datatableview
        args: ['--recursive', '--diff']
