sudo: false
language: python
python:
  - "2.7"
  - "3.4"
env:
  # - DJANGO=1.4.22
  # - DJANGO=1.5.12
  # - DJANGO=1.6.11
  - DJANGO=1.7.11
  - DJANGO=1.8.15
  - DJANGO=1.9.10
  - DJANGO=1.10.2
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install pyflakes
  - pip install -q -e . --use-mirrors
#before_script:
  #- "pep8 --exclude=migrations --ignore=E501,E225 datatableview"
  #- pyflakes datatableview
script:
  - if [[ "$DJANGO" < "1.7" ]]; then
        cd datatableview/tests/example_project;
        python manage.py test;
    else
        python datatableview/tests/example_project/manage.py test;
    fi

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO=1.4.22
